module.exports = [
  { palavra: "abacaxi", dica: "Fruta tropical de casca espinhosa", tema: "Frutas" },
  { palavra: "banana", dica: "Fruta amarela muito popular", tema: "Frutas" },
  { palavra: "morango", dica: "Fruta vermelha pequena com sementes por fora", tema: "Frutas" },
  { palavra: "melancia", dica: "Fruta grande e refrescante", tema: "Frutas" },
  { palavra: "laranja", dica: "Fruta citrica rica em vitamina C", tema: "Frutas" },
  { palavra: "manga", dica: "Fruta doce muito comum no Brasil", tema: "Frutas" },
  { palavra: "uva", dica: "Fruta usada para fazer vinho", tema: "Frutas" },
  { palavra: "pera", dica: "Fruta de formato alongado", tema: "Frutas" },
  { palavra: "maca", dica: "Fruta muito associada a contos de fadas", tema: "Frutas" },
  { palavra: "kiwi", dica: "Fruta pequena de polpa verde", tema: "Frutas" },

  { palavra: "elefante", dica: "Animal terrestre de grande porte com tromba", tema: "Animais" },
  { palavra: "girafa", dica: "Animal africano de pescoco comprido", tema: "Animais" },
  { palavra: "tigre", dica: "Felino listrado", tema: "Animais" },
  { palavra: "coelho", dica: "Animal famoso na pascoa", tema: "Animais" },
  { palavra: "cachorro", dica: "Melhor amigo do homem", tema: "Animais" },
  { palavra: "gato", dica: "Felino domestico", tema: "Animais" },
  { palavra: "zebra", dica: "Animal de listras pretas e brancas", tema: "Animais" },
  { palavra: "macaco", dica: "Animal conhecido por subir em arvores", tema: "Animais" },
  { palavra: "jacare", dica: "Reptil de rio com dentes afiados", tema: "Animais" },
  { palavra: "pinguim", dica: "Ave que vive em regioes frias", tema: "Animais" },

  { palavra: "brasil", dica: "Pais do futebol e do carnaval", tema: "Paises" },
  { palavra: "canada", dica: "Pais conhecido pelo frio e pela folha de bordo", tema: "Paises" },
  { palavra: "japao", dica: "Pais asiatico das cerejeiras", tema: "Paises" },
  { palavra: "mexico", dica: "Pais famoso por tacos e mariachis", tema: "Paises" },
  { palavra: "franca", dica: "Pais da torre eiffel", tema: "Paises" },
  { palavra: "italia", dica: "Pais da pizza e da bota", tema: "Paises" },
  { palavra: "argentina", dica: "Pais vizinho conhecido pelo tango", tema: "Paises" },
  { palavra: "egito", dica: "Pais das piramides", tema: "Paises" },
  { palavra: "india", dica: "Pais do taj mahal", tema: "Paises" },
  { palavra: "espanha", dica: "Pais europeu das touradas", tema: "Paises" },

  { palavra: "futebol", dica: "Esporte com bola e 11 jogadores", tema: "Esportes" },
  { palavra: "natacao", dica: "Esporte praticado na agua", tema: "Esportes" },
  { palavra: "volei", dica: "Esporte de rede muito popular no Brasil", tema: "Esportes" },
  { palavra: "basquete", dica: "Esporte jogado com cesta", tema: "Esportes" },
  { palavra: "tenis", dica: "Esporte com raquete e quadra", tema: "Esportes" },
  { palavra: "xadrez", dica: "Esporte mental com rei e rainha", tema: "Esportes" },
  { palavra: "surf", dica: "Esporte praticado sobre ondas", tema: "Esportes" },
  { palavra: "karate", dica: "Arte marcial japonesa", tema: "Esportes" },
  { palavra: "handebol", dica: "Esporte parecido com futebol, mas com as maos", tema: "Esportes" },
  { palavra: "ciclismo", dica: "Esporte com bicicleta", tema: "Esportes" },

  { palavra: "camiseta", dica: "Roupa usada na parte de cima do corpo", tema: "Roupas" },
  { palavra: "calca", dica: "Roupa que cobre as pernas", tema: "Roupas" },
  { palavra: "sapato", dica: "Calcado social ou casual", tema: "Roupas" },
  { palavra: "vestido", dica: "Peca unica muito usada em ocasioes especiais", tema: "Roupas" },
  { palavra: "jaqueta", dica: "Roupa para dias frios", tema: "Roupas" },
  { palavra: "gravata", dica: "Acessorio comum em roupas formais", tema: "Roupas" },
  { palavra: "meias", dica: "Peca usada nos pes, dentro do calcado", tema: "Roupas" },
  { palavra: "bermuda", dica: "Roupa curta para dias quentes", tema: "Roupas" },
  { palavra: "sandalia", dica: "Calcado aberto", tema: "Roupas" },
  { palavra: "bone", dica: "Acessorio usado na cabeca contra o sol", tema: "Roupas" },

  { palavra: "martelo", dica: "Ferramenta usada para pregos", tema: "Objetos" },
  { palavra: "tesoura", dica: "Objeto usado para cortar papel", tema: "Objetos" },
  { palavra: "janela", dica: "Abertura para luz e ventilacao", tema: "Objetos" },
  { palavra: "cadeira", dica: "Movel para sentar", tema: "Objetos" },
  { palavra: "espelho", dica: "Objeto que reflete imagem", tema: "Objetos" },
  { palavra: "garrafa", dica: "Recipiente para liquidos", tema: "Objetos" },
  { palavra: "mochila", dica: "Usada para carregar materiais nas costas", tema: "Objetos" },
  { palavra: "escova", dica: "Objeto de higiene ou para cabelo", tema: "Objetos" },
  { palavra: "relogio", dica: "Objeto que marca as horas", tema: "Objetos" },
  { palavra: "almofada", dica: "Objeto macio de sofa ou cama", tema: "Objetos" },

  { palavra: "arroz", dica: "Alimento muito presente no prato brasileiro", tema: "Comidas" },
  { palavra: "feijao", dica: "Combina muito com arroz", tema: "Comidas" },
  { palavra: "lasanha", dica: "Massa em camadas", tema: "Comidas" },
  { palavra: "pizza", dica: "Prato redondo muito popular", tema: "Comidas" },
  { palavra: "hamburguer", dica: "Lanche com pao e carne", tema: "Comidas" },
  { palavra: "sorvete", dica: "Sobremesa gelada", tema: "Comidas" },
  { palavra: "brigadeiro", dica: "Doce tipico de festas", tema: "Comidas" },
  { palavra: "macarrao", dica: "Massa muito consumida", tema: "Comidas" },
  { palavra: "omelete", dica: "Prato feito com ovos", tema: "Comidas" },
  { palavra: "pipoca", dica: "Lanche classico de cinema", tema: "Comidas" },

  { palavra: "vermelho", dica: "Cor associada a paixao", tema: "Cores" },
  { palavra: "azul", dica: "Cor do ceu em dia limpo", tema: "Cores" },
  { palavra: "amarelo", dica: "Cor do sol e de muitas frutas", tema: "Cores" },
  { palavra: "verde", dica: "Cor da natureza", tema: "Cores" },
  { palavra: "roxo", dica: "Cor entre azul e vermelho", tema: "Cores" },
  { palavra: "laranja", dica: "Cor e tambem nome de fruta", tema: "Cores" },
  { palavra: "branco", dica: "Cor associada a paz", tema: "Cores" },
  { palavra: "preto", dica: "Cor da ausencia de luz", tema: "Cores" },
  { palavra: "cinza", dica: "Cor entre preto e branco", tema: "Cores" },
  { palavra: "rosa", dica: "Cor muito associada a uma flor", tema: "Cores" },

  { palavra: "violao", dica: "Instrumento de cordas muito popular", tema: "Instrumentos musicais" },
  { palavra: "piano", dica: "Instrumento com teclas", tema: "Instrumentos musicais" },
  { palavra: "flauta", dica: "Instrumento de sopro", tema: "Instrumentos musicais" },
  { palavra: "bateria", dica: "Conjunto de tambores de uma banda", tema: "Instrumentos musicais" },
  { palavra: "trompete", dica: "Instrumento de metal e sopro", tema: "Instrumentos musicais" },
  { palavra: "saxofone", dica: "Instrumento muito ligado ao jazz", tema: "Instrumentos musicais" },
  { palavra: "violino", dica: "Instrumento de cordas tocado com arco", tema: "Instrumentos musicais" },
  { palavra: "cavaquinho", dica: "Instrumento comum no samba", tema: "Instrumentos musicais" },
  { palavra: "tambor", dica: "Instrumento de percussao", tema: "Instrumentos musicais" },
  { palavra: "guitarra", dica: "Instrumento eletrico de cordas", tema: "Instrumentos musicais" }
];
